;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        dired-do-rename
        isearch-abort
        isearch-printing-char
        kill-region
        magit-revert-item
        mark-sexp
        mozc-handle-event
        my-backward-indent
        phi-search
        wdired-next-line
        wdired-previous-line
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        dired-toggle-read-only
        git-rebase-squash
        handle-switch-frame
        make-frame
        my-mc/mark-next-and-cycle-forward
        wdired-finish-edit
        ))
