;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        isearch-abort
        isearch-printing-char
        magit-revert-item
        mark-sexp
        mozc-handle-event
        my-backward-indent
        phi-search
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        my-mc/mark-next-and-cycle-forward
        ))
